apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-vault
  template:
    metadata:
      labels:
        app: consul-vault
    spec:
      containers:
      - name: consul
        image: consul.azurecr.io/consul 
        ports:
        - containerPort: 8501
        env:
        - name: consul
          value: "consul-ubuntu"
      - name: vault
        image: consul.azurecr.io/vault
        ports:
        - containerPort: 8200
        env:
        - name: vault
          value: "vault-ubuntu"
      imagePullSecrets:
      - name: secret-bhanu
---
apiVersion: v1
kind: Service
metadata:
  name: consul-vault
spec:
  type: LoadBalancer
  ports:
  - name: consul
    protocol: TCP
    port: 8501
    targetPort: 8501
  - name: vault
    protocol: TCP
    port: 8200
    targetPort: 8200
  selector:
    app: consul-vault

